veracode_static_scan:
  push:
    trigger: true
    branches_to_run:
      - '*'  # Runs on all branches
    branches_to_exclude: []  # Empty to avoid syntax errors
  pull_request:
    trigger: true
    action:
      - opened
      - synchronize
    target_branch:
      - default_branch  # Replace with the actual name of your default branch
  analysis_on_platform: true
  break_build_policy_findings: false
  break_build_invalid_policy: false
  break_build_on_error: false
  error_message: "Veracode static scan faced a problem. Please contact your Veracode administrator for more information."
  policy: 'Veracode Recommended Medium + SCA'
  create_code_scanning_alert: false
  create_issue: false
  issues:
    trigger: false
    commands:
      - "Veracode Static Scan"

# Commented out SCA scan portion
# veracode_sca_scan:
#   push:
#     trigger: true
#     branches_to_run:
#       - '*'  # Runs on all branches
#     branches_to_exclude: []  # Empty to avoid syntax errors
#   pull_request:
#     trigger: true
#     action:
#       - opened
#       - synchronize
#     target_branch:
#       - default_branch  # Replace with the actual name of your default branch
#   break_build_on_error: false
#   error_message: "Veracode SCA scan faced a problem. Please contact your Veracode administrator for more information."
#   issues:
#     trigger: false
#     commands:
#       - "Veracode SCA Scan"

# Commented out IaC secrets scan portion
# veracode_iac_secrets_scan:
#   push:
#     trigger: false
#     branches_to_run:
#       - '*'  # Runs on all branches
#     branches_to_exclude: []  # Empty to avoid syntax errors
#   pull_request:
#     trigger: false
#     action:
#       - opened
#       - synchronize
#     target_branch:
#       - default_branch  # Replace with the actual name of your default branch
#   break_build_policy_findings: false
#   break_build_on_error: false
#   error_message: "Veracode IAC secrets scan faced a problem. Please contact your Veracode administrator for more information."
#   issues:
#     trigger: false
#     commands:
#       - "Veracode IAC Scan"
