name: Veracode Scans

on:
  push:
    branches:
      - '*'  # Trigger on all branches
  pull_request:
    branches:
      - main  # Replace with your actual default branch name

jobs:
  veracode_static_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x' # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build # Adjust this if your build command is different

      - name: Package binaries
        run: zip -r build.zip . # Package the build output

      - name: Upload binaries to Veracode for SAST
        uses: veracode/veracode-upload-and-scan-action@v1.4.3
        with:
          api_id: ${{ secrets.VERACODE_API_ID }}
          api_key: ${{ secrets.VERACODE_API_KEY }}
          app_name: ${{ github.repository }}
          sandbox_name: 'Default Sandbox'
          file_path: 'build.zip'
          scan_type: 'static'
          analysis_on_platform: true
          break_build_policy_findings: false
          break_build_invalid_policy: false
          break_build_on_error: false
          policy: 'Veracode Recommended Medium + SCA'
          create_code_scanning_alert: false
          create_issue: false
          error_message: "Veracode static scan faced a problem. Please contact your Veracode administrator for more information."

  veracode_sca_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Upload code to Veracode for SCA
        uses: veracode/veracode-upload-and-scan-action@v1.4.3
        with:
          api_id: ${{ secrets.VERACODE_API_ID }}
          api_key: ${{ secrets.VERACODE_API_KEY }}
          app_name: ${{ github.repository }}
          sandbox_name: 'Default Sandbox'
          file_path: '.'
          scan_type: 'sca'
          break_build_on_error: false
          error_message: "Veracode SCA scan faced a problem. Please contact your Veracode administrator for more information."

  veracode_iac_secrets_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Upload code to Veracode for IAC/Secrets Scan
        uses: veracode/veracode-upload-and-scan-action@v1.4.3
        with:
          api_id: ${{ secrets.VERACODE_API_ID }}
          api_key: ${{ secrets.VERACODE_API_KEY }}
          app_name: ${{ github.repository }}
          sandbox_name: 'Default Sandbox'
          file_path: '.'
          scan_type: 'iac_secrets'
          break_build_on_error: false
          error_message: "Veracode IAC secrets scan faced a problem. Please contact your Veracode administrator for more information."
